### PR TITLE
Fix PhotonVisionIOSim

### PR DESCRIPTION
**Pull request by Emma03L**
Check if `estimatedPose` is empty before proceeding in `PhotonVisionIOSim` in `updateInputs()`.

### CODE REVIEW

**Review by katzuv — COMMENTED** [review]
Why is that needed? In general, why does this IO know about the estimator? This should be handled in the subsystem, and you should log **all** inputs.

**Comment by Emma03L** [comment]
So should `poseFieldOriented` and `timestamp` be an output?

**Comment by katzuv** [comment]
> So should `poseFieldOriented` and `timestamp` be an output?

No, because they are inputs – everything you get from hardware (including external coprocessors) should be treated as an input. You can also say that if you can't reproduce something in replay, it's an input.

**Review by rakrakon — COMMENTED** [review]
I think this PR can be closed. It's already been taken care of in  #84

**Pull request closed without merging**
